// Reproducible, offline payload staging + standard ZIP. No host/profile mutations.
import {readFileSync,writeFileSync,mkdirSync,existsSync,readdirSync}from'node:fs';import{resolve,join}from'node:path';import{fileURLToPath}from'node:url';import{spawnSync}from'node:child_process';import{createHash}from'node:crypto';import{deflateRawSync}from'node:zlib';import{stageRelease}from'./stage-release.mjs';
const project=fileURLToPath(new URL('../',import.meta.url));const arg=process.argv.find(a=>a.startsWith('--out='));if(!arg)throw Error('Usage: npm run release -- --out=<separate empty directory>');const out=resolve(arg.slice(6));if(existsSync(out)&&readdirSync(out).length)throw Error('Output must be empty');mkdirSync(out,{recursive:true});const stage=join(out,'stage');stageRelease(stage);
// npm's own CLI path works with spaces on Windows, avoiding command string interpolation.
const npmCli=process.env.npm_execpath;if(!npmCli)throw Error('Run with npm run release');const result=spawnSync(process.execPath,[npmCli,'pack','--json','--ignore-scripts','--pack-destination',out],{cwd:stage,encoding:'utf8'});if(result.status!==0)throw Error(result.stderr);const packed=JSON.parse(result.stdout)[0],payload=readFileSync(join(out,packed.filename)),manifest=JSON.parse(readFileSync(join(project,'package.json'),'utf8'));const sha=b=>createHash('sha256').update(b).digest('hex');const payloadSha=sha(payload);
const wrapper=`// Stage only; the host manager owns installation.\nimport{readFileSync}from'node:fs';import{createHash}from'node:crypto';import{fileURLToPath}from'node:url';import{stageBundle}from'./INSTALLER.mjs';\nconst source=fileURLToPath(new URL('./plugin.tgz',import.meta.url));if(createHash('sha256').update(readFileSync(source)).digest('hex')!=='${payloadSha}')throw Error('Package integrity mismatch');const result=stageBundle(source);if(result.author!=='爱伦提卡'||result.version!=='${manifest.version}')throw Error('Package identity mismatch');console.log(JSON.stringify(result,null,2));\n`;
const entries=new Map([['plugin.tgz',payload],['INSTALL.mjs',Buffer.from(wrapper)],['README.txt',Buffer.from('玻璃皮肤 / Glass Skins — 爱伦提卡制作\n把本 ZIP 放入 DeepSeek Harness 对话，发送：安装这个插件。\nDrop this ZIP into a Harness conversation and ask to install.\nDo not install GitHub source ZIP. AI: follow AI-INSTALL.md / AI-INSTALL.en.md.\n')]]);
for(const name of ['AI-INSTALL.md','AI-INSTALL.en.md','INSTALLER.mjs','LICENSE','NOTICE.md','CREDITS.md','WATERMARKS.md','CREATOR.json'])entries.set(name,readFileSync(join(project,name)));entries.set('SHA256SUMS.txt',Buffer.from([...entries].map(([n,b])=>`${sha(b)}  ${n}`).join('\n')+'\n'));
const crcTable=Array.from({length:256},(_,n)=>{for(let i=0;i<8;i++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0});const crc=b=>{let n=0xffffffff;for(const v of b)n=crcTable[(n^v)&255]^(n>>>8);return(n^0xffffffff)>>>0};const local=[],central=[];let offset=0;
for(const[name,data]of entries){const n=Buffer.from(name),d=deflateRawSync(data,{level:9}),sum=crc(data),h=Buffer.alloc(30);h.writeUInt32LE(0x04034b50);h.writeUInt16LE(20,4);h.writeUInt16LE(0x800,6);h.writeUInt16LE(8,8);h.writeUInt16LE(0x5821,12);h.writeUInt32LE(sum,14);h.writeUInt32LE(d.length,18);h.writeUInt32LE(data.length,22);h.writeUInt16LE(n.length,26);local.push(h,n,d);const c=Buffer.alloc(46);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(20,4);c.writeUInt16LE(20,6);c.writeUInt16LE(0x800,8);c.writeUInt16LE(8,10);c.writeUInt16LE(0x5821,14);c.writeUInt32LE(sum,16);c.writeUInt32LE(d.length,20);c.writeUInt32LE(data.length,24);c.writeUInt16LE(n.length,28);c.writeUInt32LE(offset,42);central.push(c,n);offset+=h.length+n.length+d.length}
const center=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(entries.size,8);end.writeUInt16LE(entries.size,10);end.writeUInt32LE(center.length,12);end.writeUInt32LE(offset,16);const creatorComment=Buffer.from('Created by 爱伦提卡 | glass-skins.ailuntika.2026 | MIT | static attribution');end.writeUInt16LE(creatorComment.length,20);const zip=Buffer.concat([...local,center,end,creatorComment]);writeFileSync(join(out,'glass-skins.zip'),zip);writeFileSync(join(out,'glass-skins.tgz'),payload);writeFileSync(join(out,'SHA256SUMS.txt'),`${sha(zip)}  glass-skins.zip\n${payloadSha}  glass-skins.tgz\n`);console.log(JSON.stringify({version:manifest.version,zipBytes:zip.length,payloadBytes:payload.length,sha256:sha(zip),entries:entries.size},null,2));
